name: interop

on:
  push:
    branches:
    - sat-debug

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - name: Build and publish interop docker image
      uses: docker/build-push-action@v3
      with:
        context: interop
        push: true
        tags: ghcr.io/ngtcp2/ngtcp2-interop:sat-debug
